### ISSUE TITLE
Potential new issue placeholder

### ISSUE THREAD

**Issue by igr** [oblac/jodd-http#7]
@neroux you mentioned something about the issue? :)

**Comment by neroux** [comment]
I did, but then I double checked 😆. Apologies, my bad.

I used `addHeader()` instead of `setHeader()` and got two user agent headers.

Only thing, I believe the description is not entirely accurate.

https://github.com/oblac/jodd-http/blob/720a304ee8db25429c69922b21f6587e0a408dc4/src/main/java/jodd/http/HeadersMultiMap.java#L36-L39

**Comment by igr** [comment]
Ah, true... HTTP headers are so crazy. We can have one, we can have multiple... fun :)))

**Comment by neroux** [comment]
Though not all headers like that. Yep, fun :)
